### ISSUE TITLE
archive_file data source gets created during "terraform plan" vs "terraform apply" and also is not deleted during destroy

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-archive#218]
### Terraform CLI and Provider Versions

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/google v4.66.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Terraform Configuration

```terraform
terraform {
  required_providers {
    archive = {
      version = ">= 2.3.0"
    }
}

data "archive_file" "source_files" {
  type        = "zip"
  output_path = "${path.module}/src.zip"

  source {
    content  = file("${path.module}/requirements.txt")
    filename = "requirements.txt"
  }

  source {
    content  = file("${path.module}/main.py")
    filename = "main.py"
  }
}
```

### Expected Behavior

I would expect that:

(1) The archive file would not be created during "terraform plan"
(2) The archive file would be created during "terraform apply"
(3) The archive file would be deleted during "terraform destroy"

### Actual Behavior

(1) The archive file is created during "terraform plan"
(2) The archive file is not destroyed during "terraform destroy"

### Steps to Reproduce

Terraform command: 1.4.6
archive provider: 2.3.0

To replicate

(1) Create some source files.  I am using main.py and requirements.txt but they can be any files.

(2) Create a tf file that contains the following.

terraform {
  required_providers {
    archive = {
      version = ">= 2.3.0"
    }
}

data "archive_file" "source_files" {
  type        = "zip"
  output_path = "${path.module}/src.zip"

  source {
    content  = file("${path.module}/requirements.txt")
    filename = "requirements.txt"
  }

  source {
    content  = file("${path.module}/main.py")
    filename = "main.py"
  }
}

(3) Run "terraform plan --out=plan.out"

You will see that src.zip has been created during "terraform plan" rather than waiting for "terraform apply"

(4) terraform apply

(5) terraform destroy

src.zip continues to exist

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @jeffscottlevine 👋 

It sounds like you might need to use the [archive_file resource](https://registry.terraform.io/providers/hashicorp/archive/latest/docs/resources/file) rather than the data source in this instance. Could you try using the resource and see if that behaves in the way that you are expecting?

**Comment by bendbennett** [comment]
Although the archive_file resource is marked as deprecated, there are currently no plans to remove it.

**Comment by Console32** [comment]
Can you remove the deprecation note? The datasource is no replacement for the archive_file resource.

**Comment by robertbrandso** [comment]
I very much agree with @Console32, the data source is no replacement for the archive_file resource.

One use case is when I need something to happen before the zip is created. When the zip is created during plan this is rather difficult to do.

**Comment by raphael-ratepay** [comment]
@bendbennett would it be possible to remove the deprecation note?

**Comment by Hronom** [comment]
Would it be possible to remove deprecation note?

There strong use case for it. In our case when we work with lambdas in AWS.

**Comment by bendbennett** [comment]
We will discuss removal of the deprecation note from the archive resource within the team and provide feedback once a conclusion has been reached.

**Comment by bwhaley** [comment]
Can you explain the difference between the resource and the data source? The docs do not explain what the difference is. 

Also it's extremely confusing for you to suggest to use the resource if it says right at the top of the page to use the data source instead.

**Comment by socketbox** [comment]
It looks as if the deprecation is proceeding, as I've just encountered this message in `apply` output:
```
│ Warning: Deprecated                                                                            
│                                                                                                
│   with module.lite.module.pbsorg.archive_file.lambda_archive,                                  
│   on pbsorg/resources/notifications.tf line 25, in resource "archive_file" "lambda_archive":   
│   25: resource "archive_file" "lambda_archive" {                                               
│                                                                                                
│ **NOTE**: This resource is deprecated, use data source instead.                                
│                                                                                                
│ (and 2 more similar warnings elsewhere)                                                        
╵                                                                                                
```

**Comment by novekm** [comment]
Any updates on this? I'm currently using the `archive_file` data source but as others have mentioned, the archive is created during `plan` instead of during `apply`, and such does not get deleted when running `terraform destroy`. I'm using it in a module that will released by AWS, so would prefer to not have the warning that @socketbox mentioned.

**Comment by SergiiKrupenko-cnic** [comment]
I use data.archive_file to and this causes a problem when dir for zip is deleted and will be recreated after **terraform apply** because it's a lambda layer. So for now I plan to change to resource archive_file or may be some one can advise better solution.

**Comment by EAR009** [comment]
I am also facing same issue where the terraform plan is successful but apply fails. Is there any concrete response to resolve this long pending issue?

**Comment by codymaust** [comment]
@bendbennett and the rest of the contributing team, please consider this pull request

https://github.com/hashicorp/terraform-provider-archive/pull/367

thanks!

**Comment by wayneworkman** [comment]
I wanted to provide my use case. I do not consider this a bug. I depend on Terraform outputting the source_code_hash for AWS Lambdas during Terraform plans. At work, we use these Terraform plans for our deployment approval processes and it’s crucial that the SHA256 Base64 encoded checksum of Lambda packages be present within Terraform plan output. This checksum within an approved Terraform plan is the easiest way to actually validate that the Lambda package currently deployed in AWS matches the approved Terraform plans.

So my request is, please do not take any actions on this because in my use case it is working exactly as needed.

**Comment by EAR009** [comment]
Yes it will work for very few use case like yours. In general, the replacement is not working.

> I wanted to provide my use case. I depend on Terraform outputting the source_code_hash for AWS Lambdas during Terraform plans. At work, we use these Terraform plans for our deployment approval processes and it’s crucial that the SHA256 Base64 encoded checksum of Lambda packages be present within Terraform plan output. This checksum within an approved Terraform plan is the easiest way to actually validate that the Lambda package currently deployed in AWS matches the approved Terraform plans.

**Comment by SBGoods** [comment]
[v2.7.0](https://github.com/hashicorp/terraform-provider-archive/releases/tag/v2.7.0) has just been released with the removal of the `archive_file` resource deprecation has just been released. I wasn't able to get the guide for the provider documentation in but I didn't want that to block the release. Hopefully, we will get the documentation in with a patch after the holidays.
