### ISSUE TITLE
Support Additional Compression Types(Ex: tar.gz format)

### ISSUE THREAD

**Issue by srikanth2302** [hashicorp/terraform-provider-archive#241]
### Terraform CLI and Provider Versions

Terraform v1.3.6

archive = {
  source = "hashicorp/archive"
  version = "2.4.0"
}

### Use Cases or Problem Statement

It would be useful if we can support multiple Archive types such as tar.gz for linux.. Because.. we dont need to install unzip package in linux as tar is by default in it.

### Proposal

Add Support for tar.gz type archive filr

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @srikanth2302 👋 

Thank you for raising this issue.
We will leave the issue open and prioritise according to the amount of community interest that is expressed.

**Comment by achetronic** [comment]
Hello there, I would love to have this implemented for ISO files. 

A usage case is being able to create disks that are loaded on VM's that does not use cloud-init. For example libvirt VMs using Talos, which can be configured loading an .iso image with a YAML inside

**Comment by fsdrw08** [comment]
any updates?

**Comment by jkroepke** [comment]
In case, you are looking for tar.gz, take a look here and vote for it: https://github.com/hashicorp/terraform-provider-archive/pull/277
