### ISSUE TITLE
archive_file produces a corrupted zip file

### ISSUE THREAD

**Issue by AbirHamzi** [hashicorp/terraform-provider-archive#282]
### Terraform CLI and Provider Versions

Terraform v1.6.5
Provider v2.4.0

### Terraform Configuration

```terraform
resource "archive_file" "my-archive" {
  type             = "zip"
  source_dir       = "my-code"
  output_path      = "my-code.zip"

}
```

### Expected Behavior

I expect to see the same number of compressed files as the CLI zip command and I can run the unzip command without problems.

### Actual Behavior

my-code.zip: compressed by archive_file
my-code1.zip: compressed by the zip command

$ zipinfo my-code.zip
2184 files, 21307869 bytes uncompressed, 13355944 bytes compressed:  37.3%

$ zipinfo my-code1.zip
3057 files, 21307869 bytes uncompressed, 13302202 bytes compressed:  37.6%

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicolasiscoding** [comment]
I am seeing the same issue

**Comment by ricardo-vargas-globant** [comment]
hi, I am facing the same issue with this module, this is happening in aws code pipeline when I am trying to deploy a lambda function compressing the code. 
These are the steps my pipeline does
* Download terraform **(version 1.5.4),** 
* Run script to install as part of the lambda function the dependencies
* Run terraform init **(use archive version 2.4.0)**
* Run terraform plan (here detects changes in lambda and dependencies even when nothing has changed)
* Run terraform apply (fails bc the zip fail can be unzipped) 

```
  ~ resource "aws_lambda_function" "executor" {
        id                             = "XXXX-XXX"
      ~ last_modified                  = "2023-12-14T18:26:58.114+0000" -> (known after apply)
      ~ source_code_hash               = "TLjOA7sHL0aqCELeiTvHOvgQ5udziIsqT0jzRw4fX7c=" -> "ktFmbHiFVN26iyGz0ULweoAV8lnUibpMDgN/79GrfWc=" # For some reason shows different hash code
        tags                           = {
            "Name"         =  "XXXX-XXX"
            "app"          = "data"
            "creation_app" = "terraform"
            "env"          = "d1"
            "site"         = "aue1"
            "tier"         = "data"
            "zone"         = "z1"
        }
        # (21 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }
```

Error during the apply 

```Error: updating Lambda Function ("XXXX-XXX") code: operation error Lambda: UpdateFunctionCode, https response error StatusCode: 400, RequestID: 8a818ada-9e06-4126-8666-8ef6270629d2, InvalidParameterValueException: Failed to unzip archive: An error in the archive format was detected. Please fix the error and retry;```

I tried to replicate this locally and I did it once, after that the module have been working as expected. 

As @AbirHamzi mentioned, the size of the generated file is smaller than the expected and it's not possible to open the file.

**Comment by AbirHamzi** [comment]
I'm closing this issue because my problem has been resolved. Even though the number of files compressed with 'archive_file' is not the same as those compressed with the 'zip' command, it was not the reason why my file is corrupted
