### ISSUE TITLE
Force file mode inside archive

### ISSUE THREAD

**Issue by Supermathie** [hashicorp/terraform-provider-archive#53]
We've discovered that the file mode of source files is now preserved by `archive_file`. While we recognize *everybody* has different requirements, we think it would be useful to be able to specify a mode for files either for the entire archive or for a single `source`.

Especially given how often this seems to rear its head. Would you welcome a PR on this?

### Terraform Version
Terraform v0.12.12
+ provider.archive v1.3.0
+ provider.aws v2.34.0
+ provider.external v1.2.0
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- archive_file

### Terraform Configuration Files
```hcl
data "archive_file" "snapshot_replica" {
  type        = "zip"
  source_file = "${path.module}/snapshot-replica-lambda/index.js"
  output_path = "${path.module}/snapshot-replica-lambda/snapshot-replica-lambda.zip"
}
```

### Debug Output
(can provide)

### Expected Behavior
The sha256sum of the generated zipfile is consistent across machines. This seems to be the expectation implied by #10.

### Actual Behavior
The sha256sum of the generated zipfile differs depending on the mode of the source file in the archive.

### Steps to Reproduce
1. On Computer A, index.js has the mode `0644` (it has a umask of 0022)
1. On Computer B, index.js has the mode `0664` (it has a umask of 0002)
1. `tf plan` on both machines
1. The generated archive differs as follows:

```
○ → zipinfo kronos-snapshot-replica-lambda.zip 
Archive:  kronos-snapshot-replica-lambda.zip
Zip file size: 815 bytes, number of entries: 1
-rw-r--r--  2.0 unx     1951 bl defN 49-Jan-01 00:00 index.js
1 file, 1951 bytes uncompressed, 685 bytes compressed:  64.9%

○ → zipinfo challenger-snapshot-replica-lambda.zip 
Archive:  challenger-snapshot-replica-lambda.zip
Zip file size: 815 bytes, number of entries: 1
-rw-rw-r--  2.0 unx     1951 bl defN 49-Jan-01 00:00 index.js
1 file, 1951 bytes uncompressed, 685 bytes compressed:  64.9%
```

**Comment by appilon** [comment]
Hello @Supermathie our apologies for not responding sooner. It appears this issue, #10 #58 #34 are all related. It appears the permissions being misset across operating systems is problematic for a number of reasons, but a popular one being #34 . Yes we would be willing accept a PR enhancing the provider with the ability to force file mode within the archive. There have been similar attempts in #41 and #47. I can devote time to this soon.

**Comment by riking** [comment]
Note: We now correct the permissions in the wrapper Makefile.
