### ISSUE TITLE
Run 

### ISSUE THREAD

**Issue by Eslamanwar** [hashicorp/terraform-provider-archive#75]
Hi there,

- we have lambda function that have 3 python files and 1 requirements file, we use Gitops and store all our files here on git, we need to upload only thr 3 python files (not all source files and dependencies), so we need the build_command to run every terraform apply is run. in current case only when the lambda creation.

### Terraform Version
v0.12.19

### Affected Resource(s)
Please list the resources as a list, for example:
- lambda function

**Comment by kmoe** [comment]
This does not appear to describe a bug in terraform-provider-archive. Please open an issue against the appropriate Terraform provider or module. If you believe this repository is the correct place for this report, please reopen this issue and edit the description to fill in the whole issue template: https://github.com/hashicorp/terraform-provider-archive/blob/main/.github/ISSUE_TEMPLATE.md.
